matching_obj = {
    "Doğalgaz": "Doğalgazlı",
    "Duos": "Dual",
    "Garantiili": "Garantili",
    "Türkiye": "Distribütor",
    "Sim": "Dual",
    "Makinası": "Makinesi",
    "Kulak içi": "Kulakiçi",
    "Notebook": "Laptop",
    " Bt ": "Btooth",
    "Bluetooth": "Btoooth",
    "Goldmaster": "Gldmaster",
    "Redmi": "Rdmi",
    "FHD": "FullHD",
    "Faber-castell": "Faber Castell",
    "256G": "256GB",
    "Ryzen 7": "Ryzen7",
    "256SSD": "256GB SSD",
    "24/24": "24",
    "Travel": "Seyahat",
    "Elektirikli": "Elektrikli",
    "2 In 1": "2In1",
    "3 In 1": "3In1",
    "156''": "15\"",
    "156\"": "15\"",
    "15,6\"": "15\"",
    "13-14\"": "13\"",
    "13-14": "13\"",
    "Coral": "Mercan",
    "Roze": "Rose",
    "Safir Mavi": "Açık mavi",
    "Yellow": "Sarı",
}

checking_obj = {
    "Kulakiçi": "Kulaküstü"
}

measurement_units = [
    "gram",
    "g",
    "gr",
    "kilogram",
    "kilo",
    "kl",
    "kg",
    "inc",
    "inç",
    "santimetre",
    "cm",
    "centimetre",
    "cm²",
    "m²",
    "metre",
    "m",
    "km²",
    "kilometre",
    "km",
    "litre",
    "lt",
    "l",
    "lt/h",
    "cl",
    "mbps",
    "saat",
    "dakika",
    "dk",
    "saniye",
    "sn",
    "mm",
    "milimetre",
    "rpm",
    "miligram",
    "mg",
    "ml",
    "mililitre",
    "bit",
    "byte",
    "kb",
    "kilobyte",
    "kilobayt",
    "kcal",
    "kcal/h"
    "gbps",
    "mb",
    "megabyte",
    "megabayt",
    "gigabyte",
    "gigabayt",
    "gb",
    "terabyte",
    "terabayt",
    "tb",
    "hz",
    "ohm",
    "khz",
    "gün",
    "db",
    "w",
    "watt",
    "mah",
    "pa",
    "bar",
    "adet",
    "tane",
    "yaş",
    "ay",
    "ms",
    "millisecond",
    "milisaniye",
    "pixel",
    "piksel",
    "mp",
    "megapixel",
    "megapiksel",
    "kişi",
    "vites",
    "jant",
    "volt",
    "kilowatt",
    "ghz",
    "mbps",
    "ton",
    "%",
    "fps",
    "ppı",
    "ppi",
    "nm",
    "nanometre",
    "puan",
    "çekirdek",
    "pa",
    "mw",
    "wh",
    "mhz",
    "İnç",
    "kwh",
    "°c",
    "°",
    "sa",
    "kw",
    "btu",
    "dk/döngü",
    "dev/dk",
    "mb/s",
    "tbw",
    "darbe/dk",
    "sf/dk",
    "sayfa",
    "m3/sa",
    "kademe",
    "kg/dk",
    "hp",
    "kare/sn",
    "dpi",
    "dbi",
    "m³/saat",
    "Mbit/s",
]